version: "3.9"
services:
  minecraft-newlifesmp:
    build:
      context: ./
      dockerfile: Dockerfile
    stop_signal: SIGTERM
    ports:
      - "25565:25565"
    volumes:
      # Mount state dirs
      - ./mount/logs:/var/minecraft/logs
      - ./mount/world:/var/minecraft/world
      # Mount config files
      - ./mount/ops.json:/var/minecraft/ops.json
      - ./mount/whitelist.json:/var/minecraft/whitelist.json
      - ./mount/server.properties:/var/minecraft/server.properties
      - ./mount/eula.txt:/var/minecraft/eula.txt
    environment:
      JAVA_ARGS: "-Xmx6G"